name: Generate Examples
on:
  issue_comment:
  workflow_dispatch:

jobs:
  generate_examples:
    name: Generate diagrams on issue comment
    if: ${{ !github.event.issues.pull_request && github.event.issue.number == 4 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: example

      - name: Update diagram
        run: |
          sed -i 's/^Bob->Alice : .*/Bob->Alice : hello comment ${{ github.event.comment.id }}/' examples/sequence.puml

      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg examples/sequence.puml

      - name: Echo changes
        run: |
          git status

      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Regenerated example diagram - new comment received"
